name: reown_appkit_dapp
description: An example dapp for Reown's AppKit built with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bs58: ^1.0.2
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.9
  fl_toast: ^3.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.2
  qr_flutter: ^4.0.0
  reown_appkit:
    path: ../..
  solana_web3: ^0.1.3

dev_dependencies:
  build_runner: ^2.4.7
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true
