name: reown_appkit_example
description: "Reown's AppKit modal example"

publish_to: 'none'

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  fl_toast: ^3.1.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  reown_appkit:
    path: ../..
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/abis/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
